# Generated by Django 5.0.6 on 2024-06-16 04:46

# IGNORAR ESTA MIGRACION, FUE PRUEBA

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
            ],
        ),
    ]
