# Generated by Django 5.0.6 on 2024-06-18 19:51

# MIGRACION DE LA PAG FINAL

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsDePag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcArmada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('placa_de_video', models.CharField(max_length=50)),
                ('fuente_de_poder', models.CharField(max_length=50)),
                ('gabinete', models.CharField(max_length=50)),
            ],
        ),
    ]
