# Generated by Django 5.0.6 on 2024-06-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsDePag', '0003_portatiles_delete_motherboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portatiles',
            new_name='PortatilGamer',
        ),
    ]
