# Generated by Django 5.0.6 on 2024-06-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsDePag', '0005_pcarmada_pc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortatilGamer',
        ),
    ]
