# Generated by Django 5.0.6 on 2024-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_portatil_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portatil',
            name='spects',
            field=models.CharField(max_length=500),
        ),
    ]
